### ISSUE TITLE
License

### ISSUE THREAD

**Issue by grevend-bosch** [carbynestack/cli-ng#1]
Add a detectable license into the repository, so that people who visit this repository will see it at the top of the overview page.

**Comment by sbckr** [comment]
@grevend-bosch The master branch would still be missing and needed to be created and pushed anyway. I would suggest to make a first commit of the license to  `master`

**Comment by grevend-bosch** [comment]
> @grevend-bosch The master branch would still be missing and needed to be created and pushed anyway. I would suggest to make a first commit of the license to `master`

Will @cs-minion author the initial commit?
