### ISSUE TITLE
Setup pre-commit hooks

### ISSUE THREAD

**Issue by grevend-bosch** [carbynestack/cli-ng#10]
Setup formatting and linting pre-commit hooks.

~~This initial configuration will not include a formatter for Java, because the one being used for the deprecated cli produces illegible snippets like:~~

~~https://github.com/carbynestack/cli/blob/36170a0c8a813e4b6b06d83b44b9491c68cdba36/src/main/java/io/carbynestack/cli/client/ephemeral/command/EphemeralClientCliCommandRunner.java#L37-L66~~

**Comment by grevend-bosch** [comment]
@sbckr Any thoughts?

**Comment by strieflin** [comment]
@grevend-bosch: What is the problem with the output of the code formatter. Looking at the snippet I don't see an issue. In addition, we should adhere to one common formatting style for all our Java-based components. Changing all of them would required some effort that we should only spent if the ROTI is high enough.

**Comment by sbckr** [comment]
@grevend-bosch: In general I see some potential on how to improve the formatting, but this should not lead to breaking with our own standards regarding automated formatting. 
In the long run, I can _imagine_ looking for alternative style guides or making improvements to the current configuration, but for now I'd prefer to stay with the current default.

And i agree with @strieflin, if modifications are made, they should be applied to all components.

**Comment by grevend-bosch** [comment]
> @grevend-bosch: What is the problem with the output of the code formatter. Looking at the snippet I don't see an issue. In addition, we should adhere to one common formatting style for all our Java-based components. Changing all of them would required some effort that we should only spent if the ROTI is high enough. Happy to discuss!

Specifically, [L45-46](https://github.com/carbynestack/cli/blob/36170a0c8a813e4b6b06d83b44b9491c68cdba36/src/main/java/io/carbynestack/cli/client/ephemeral/command/EphemeralClientCliCommandRunner.java#L45-L46) and [L62-65](https://github.com/carbynestack/cli/blob/36170a0c8a813e4b6b06d83b44b9491c68cdba36/src/main/java/io/carbynestack/cli/client/ephemeral/command/EphemeralClientCliCommandRunner.java#L62-L65) are very unsightly detached from the upheaval. But maybe that's just more of a problem with the use of nested lambdas and chained method calls?

I would probably have written the following instead:

```java
 Try.of(() -> {
    List<EphemeralEndpoint> endpoints =
        Arrays.stream(configuration.getProviders())
```

```java
.getOrElseThrow(t -> new CsCliRunnerException(
    getMessages().getString("client-instantiation-failed"), t));
```
**But I agree that the ROTI does not really support a change at the current stage.**

**Comment by grevend-bosch** [comment]
@strieflin @sbckr Based on both of your comments, I would summarize that we keep the current formatting for Java and put the idea of ​​revising this as a note in the backlog?
