### ISSUE TITLE
3rd Party License Obligations 

### ISSUE THREAD

**Issue by grevend-bosch** [carbynestack/cli-ng#14]
Create the *3RD-PARTY-LICENSES* directory, generate the *sbom.xml* and add dependency obligations for:

- picocli (4.6.1)
- jackson-core (2.12.3)
- scribejava-apis (8.3.1)
- Carbyne Stack APIs dependencies
  - amphora-java-client (0.1-SNAPSHOT-1261403362-2-41864d8)
  - castor-common (0.1-SNAPSHOT-1261403451-2-78f5f5b)
  - castor-java-client (0.1-SNAPSHOT-1261403451-2-78f5f5b)
  - castor-upload-java-client (0.1-SNAPSHOT-1261403451-2-78f5f5b)
  - ephemeral-java-client (0.1-SNAPSHOT-1261324039-3-d2504ed)
- and all other nested dependencies

In addition, a "3rd Party Licenses" section should be created in the readme.

**Comment by sbckr** [comment]
Reopened as `3rd Party Licenses` section is missing in the readme
