### ISSUE TITLE
GraalVM native-image compilation is failing

### ISSUE THREAD

**Issue by grevend-bosch** [carbynestack/cli-ng#92]
> Fatal error:com.oracle.graal.pointsto.util.AnalysisError$ParsingError: Error encountered while parsing io.carbynestack.httpclient.CsHttpClient.<clinit>()

> Caused by: org.graalvm.compiler.java.BytecodeParser$BytecodeParserError: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved type during parsing: org.slf4j.impl.StaticLoggerBinder.

See run output for more details:

https://github.com/carbynestack/cli-ng/runs/4561044832?check_suite_focus=true#step:15:118

**Comment by grevend** [comment]
@strieflin I believe this issue can be closed now.

**Comment by strieflin** [comment]
Seems that the issue has been resolved as the build is working now.
